version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    labels: [chore]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    labels: [chore]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
    labels: [chore]
    versioning-strategy: increase
