name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-project:
    name: Check Project
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2.0.0

      - name: Check Formatting, Linting, and Types
        run: yarn check

  build-image:
    name: Build Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Image
        run: docker build .
